
POST http://localhost/take-away/users/auth/login
Content-Type: application/json

{
    "email": "test1@example.com",
    "password": "testpassword123"
}

###

POST http://localhost/take-away/users
Content-Type: application/json

{
  "email": "test1@example.com",
  "password": "testpassword123"
}
